spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    datasource:
        platform: mariadb
        url: jdbc:mariadb://localhost:3306/PersistenceTestDB
        username: root
        password: root
        driverClassName: org.mariadb.jdbc.Driver
