spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        platform: mariadb
        url: jdbc:mariadb://localhost:3306/PersistenceTestDB2
        username: root
        password: root
        driverClassName: org.mariadb.jdbc.Driver